### ISSUE TITLE
Carbon and Tabler are the same

### ISSUE THREAD

**Issue by hananf11** [07akioni/xicons#112]
The icons for carbon and tabler are the same.
I believe this issue is caused by a typo on this line:
https://github.com/07akioni/xicons/blob/8bf05c4bcb8b9e88eddf7c5d990a8a617c7f167f/packages/xicons/scripts/config.js#L131

I think it should say `carbon` insted of `tabler`

**Comment by 07akioni** [comment]
Oops, I'll fix it.

**Comment by 07akioni** [comment]
fixed in 0.11.0
