### ISSUE TITLE
Could you please add some Chinese Website logos

### ISSUE THREAD

**Issue by gtn1024** [07akioni/xicons#113]
Could you please add some Chinese Website logos?
such as :

- [Bilibili](https://www.bilibili.com/)
- [Gitee](https://gitee.com/)

And as well, the **Groovy** programing language

**Comment by 07akioni** [comment]
xicons is focusing on integrate exisiting icon sets, however there isn't icon set which satisfy the demand.

Sorry I can't provide it.
