### ISSUE TITLE
可否新增设置自行添加图标的功能？

### ISSUE THREAD

**Issue by hanjialin** [07akioni/xicons#131]
可否新增自行添加图表的功能呢？
让UI设计完的svg批量导入到xicons中本地引用图标。
并且可以使这些图标能享受到xicon的API，方便对其进行管理。

**Comment by 07akioni** [comment]
这功能对于这个库可能太复杂了，应该是做不到的。这个库是纯静态部署，没有服务器。

**Comment by chenyulun** [comment]
完全可以，看他的源码，把里面的config都注释掉，添加自己的配置和构建过程中的替换规则
