### ISSUE TITLE
是否可以把icon包裹组件功能合并到svg组件里面

### ISSUE THREAD

**Issue by chenyulun** [07akioni/xicons#191]
每个svg组件外面必须包裹一个icon组件吗？觉得很繁琐，能不能icon组件的功能合并到svg组件里面去
单独使用svg组件好像也是可以的，可能没有全局的样式

**Comment by 07akioni** [comment]
包裹的话实际上就和具体的组件库，这咋说呢...应该是不会放在这个库里的，毕竟是组件库无关

**Comment by 07akioni** [comment]
从维护角度讲生成那么多图标其实也是个问题，现在发一次要二十多分钟😂

**Comment by chenyulun** [comment]
我构建一下，macbook Pro风扇都要炸了

**Comment by chenyulun** [comment]
其实我就是想做具体的组件库，我需要合并这些功能，你的考虑确实不错，还有就是不是很重要的图标，希望阿里fonticon的symbol注入比较合适

**Comment by 07akioni** [comment]
iconfont 我看 arco 有一个解决方案，不过我没研究具体是怎么弄的，你有时间可以参考一下

![image](https://user-images.githubusercontent.com/18677354/139654244-2cc91319-25ed-4bfb-af00-b55f743be021.png)

**Comment by 07akioni** [comment]
> 其实我就是想做具体的组件库，我需要合并这些功能，你的考虑确实不错，还有就是不是很重要的图标，希望阿里fonticon的symbol注入比较合适

至于打包的问题我觉得吧，如果你想基于这个库封装，在自己的库里写一个生成脚本是最划算的
