### ISSUE TITLE
如何动态引入图标？

### ISSUE THREAD

**Issue by yudan215** [07akioni/xicons#223]
例如使用iconicons5 antd等的图标，由用户自己选择

服务端返回对应字符串， 例如 “Add”

如何根据服务端返回的字段进行动态加载图标?

**Comment by 07akioni** [comment]
Generally you have 3 choices:

1. Create a map object in advance, the use the string for your server, like:
```
import { BirdIcon, DogIcon } from 'xxxicons/yyy'

// The methods would make your bundle size larger but its fast.
const map = {
  bird: BirdIcon,
  dog: DogIcon
}
```
2. Use the async-index provided by xicons.
```
import { BirdIcon, DogIcon } from 'xxxicons/yyy/es/async-index'

const map = {
  bird: BirdIcon,
  dog: DogIcon
}

// In this manner, the BirdIcon is like a () => Promise<VueComponent>, you can use it like a vue async component.
```
3. Save svg resources in your server and get it dynamically. In this way, it depends on yourself to serve the resources, it's not relevent with the library.

**Comment by yudan215** [comment]
第一和第二个方法都是需要提前引入所有图标组件吧，第三种应该也差不多需要把SVG都提前下载好都会导致项目的包比较大

我现在主要是有一个这样的功能·用户可选iconicon4、ionicons5、antd、material等包（最好是远程库，不需要打包在项目内）里面选择喜欢的图标，存储到后端·后端根据用户选择的·渲染到同一个项目的不同位置·最好能是动态引入的···上面的方法都是需要提前引入·导致项目包太大了，或者是否有其他解决方案

**Comment by yudan215** [comment]
第一和第二个方法都是需要提前引入所有图标组件吧，第三种应该也差不多需要把SVG都提前下载好都会导致项目的包比较大

我现在主要是有一个这样的功能·用户可选iconicon4、ionicons5、antd、material等包（最好是远程库，不需要打包在项目内）里面选择喜欢的图标，存储到后端·后端根据用户选择的·渲染到同一个项目的不同位置·最好能是动态引入的···上面的方法都是需要提前引入·导致项目包太大了，或者是否有其他解决方案

**Comment by 07akioni** [comment]
> 第一和第二个方法都是需要提前引入所有图标组件吧，第三种应该也差不多需要把SVG都提前下载好都会导致项目的包比较大
> 
> 我现在主要是有一个这样的功能·用户可选iconicon4、ionicons5、antd、material等包（最好是远程库，不需要打包在项目内）里面选择喜欢的图标，存储到后端·后端根据用户选择的·渲染到同一个项目的不同位置·最好能是动态引入的···上面的方法都是需要提前引入·导致项目包太大了，或者是否有其他解决方案

这个你可以看看 iconify，各种方案都有自己的缺点。针对你的场景要么你自己提供一个后端，要么你用别人的后端服务。

**Comment by yudan215** [comment]
后端自己写是没有问题的，主要是加载渲染图标这块

**Comment by 07akioni** [comment]
> 后端自己写是没有问题的，主要是加载渲染图标这块

如果你从后端拉的话就得看了，svg + css filter 应该可以解决很多问题。

**Comment by 07akioni** [comment]
CSS filter 是针对于 SVG img 没有颜色可以考虑的一种 hack 方式

**Comment by yudan215** [comment]
xicons是否有提供远程访问的方法··例如我选择的时候调用xicons的CDN库的··使用的时候在动态导入需要用到的在项目内

**Comment by 07akioni** [comment]
远程还得整个服务端怪麻烦的
