### ISSUE TITLE
Some icons don't show on preview site `https://www.xicons.org`

### ISSUE THREAD

**Issue by sigmarising** [07akioni/xicons#256]
![icon don't show](https://user-images.githubusercontent.com/25470568/150264512-6291bb8d-6273-412a-8b2a-fa327e73c5b0.png)

You can see from the picture above that some svg icons are not show on preview site `https://www.xicons.org`. There is no children content under the <svg> dom.

![icon which show well](https://user-images.githubusercontent.com/25470568/150264880-814dede6-b487-42ad-8089-57ec9caa9916.png)

While the icons which display properly do have contents under the <svg> dom.

**Comment by 07akioni** [comment]
Sorry for late response, I'm a bit busy these days. I'll try to fix it.

**Comment by 07akioni** [comment]
fixed in 0.12.0
