### ISSUE TITLE
Some icons are missing in material

### ISSUE THREAD

**Issue by OrbisK** [07akioni/xicons#284]
Some Icons e.g.:
![image](https://user-images.githubusercontent.com/37191683/153920076-e537bee5-da10-4404-9121-1de903ed3419.png)

Are not exported in the node modules.

**Comment by 07akioni** [comment]
Which version you are using?

**Comment by OrbisK** [comment]
`0.11.0` ill update to `0.12.0` and check quick

**Comment by OrbisK** [comment]
okay. Its there now. Just missed that update :) sorry
