### ISSUE TITLE
material 图标不能成功引入

### ISSUE THREAD

**Issue by ltxhhz** [07akioni/xicons#447]
你好，我是 Windows10 系统，没办法使用 `ulimit` 命令，我在引入 `material` 图标的时候一直不成功
![image](https://user-images.githubusercontent.com/51697596/178027924-6537f15c-8b7d-4a02-9d94-1860517d13cd.png)
之后换成引用 `fa` 图标就可以了，我看到 material 文件夹下有 21118 个项目，是否可以考虑优化一下文件数量以防止这个问题的出现，或者说这个问题不是文件数量太大导致的？

**Comment by 07akioni** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/18677354/178153943-3da0e6b5-6fc3-4624-829e-1e18d0fa4284.png">

如果改不了的话可以考虑直接用文件路径引入。

图标真的就这么多，确实没啥办法。

**Comment by ltxhhz** [comment]
@07akioni  你好，麻烦看一下我的图片哦，我图片里就是按路径引用的，但还是没能成功
