### ISSUE TITLE
Fluent icons missing

### ISSUE THREAD

**Issue by italo1983** [07akioni/xicons#50]
Hello, 
some fluent icons are missing, for example "NumberSymbolSquare24Regular", there's a planned update?

Thank you for the great work!!

**Comment by 07akioni** [comment]
@italo1983 sorry for late response. Where did you see the icon `NumberSymbolSquare24Regular`?

Previously I found there were iterating very fast and icons name can be changed a lot in different versions.

**Comment by italo1983** [comment]
@07akioni you can search for "NumberSymbolSquare24Regular" on this official repo.
https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

Thanks

**Comment by 07akioni** [comment]
> @07akioni you can search for "NumberSymbolSquare24Regular" on this official repo.
> https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md
> 
> Thanks

I've release version 0.8.0 which contains the icon, xicons site will be updated soon. @italo1983
