### ISSUE TITLE
Use Iconify as icon source

### ISSUE THREAD

**Issue by antfu** [07akioni/xicons#69]
Awesome work on this! Interesting to see the usage of different icons types!

This project seems to included 7 iconsets, which I think it's already great. I also do understand adapting more icon libraries would require much more effort. So instead of requesting for new icon collections support, how about considering use [Iconify](https://iconify.design/icon-sets/)'s collection as the data source? 

https://github.com/iconify/collections-json

@cyberalien has working really hard on collecting over 90+ icon collections into a uniformed json collection.

On top of Iconify, I also built a few tools you might be interested

- [Icones](https://icones.js.org) - Icons explorer
- [vite-plugin-icons](https://github.com/antfu/vite-plugin-icons)
- [vscode-iconify](https://github.com/antfu/vscode-iconify)
- [purge-icons](https://github.com/antfu/purge-icons)
- [Blog post - Journey with Icons](https://antfu.me/posts/journey-with-icons)

That said, I would be love to see this project adapting to reuse Iconify's collection to support much more icon collections with less effort. While providing a unified ecosystem and developer experience.

Thanks!

**Comment by 07akioni** [comment]
> Awesome work on this! Interesting to see the usage of different icons types!
> 
> This project seems to included 7 iconsets, which I think it's already great. I also do understand adapting more icon libraries would require much more effort. So instead of requesting for new icon collections support, how about considering use [Iconify](https://iconify.design/icon-sets/)'s collection as the data source?
> 
> https://github.com/iconify/collections-json
> 
> @cyberalien has working really hard on collecting over 90+ icon collections into a uniformed json collection.
> 
> On top of Iconify, I also built a few tools you might be interested
> 
> * [Icones](https://icones.js.org) - Icons explorer
> * [vite-plugin-icons](https://github.com/antfu/vite-plugin-icons)
> * [vscode-iconify](https://github.com/antfu/vscode-iconify)
> * [purge-icons](https://github.com/antfu/purge-icons)
> * [Blog post - Journey with Icons](https://antfu.me/posts/journey-with-icons)
> 
> That said, I would be love to see this project adapting to reuse Iconify's collection to support much more icon collections with less effort. While providing a unified ecosystem and developer experience.
> 
> Thanks!

I'm exploring iconify.

**Comment by 07akioni** [comment]
> Awesome work on this! Interesting to see the usage of different icons types!
> 
> This project seems to included 7 iconsets, which I think it's already great. I also do understand adapting more icon libraries would require much more effort. So instead of requesting for new icon collections support, how about considering use [Iconify](https://iconify.design/icon-sets/)'s collection as the data source?
> 
> https://github.com/iconify/collections-json
> 
> @cyberalien has working really hard on collecting over 90+ icon collections into a uniformed json collection.
> 
> On top of Iconify, I also built a few tools you might be interested
> 
> * [Icones](https://icones.js.org) - Icons explorer
> * [vite-plugin-icons](https://github.com/antfu/vite-plugin-icons)
> * [vscode-iconify](https://github.com/antfu/vscode-iconify)
> * [purge-icons](https://github.com/antfu/purge-icons)
> * [Blog post - Journey with Icons](https://antfu.me/posts/journey-with-icons)
> 
> That said, I would be love to see this project adapting to reuse Iconify's collection to support much more icon collections with less effort. While providing a unified ecosystem and developer experience.
> 
> Thanks!

Thank you for provide such useful information. I very appreciate iconify's work. I'll try to move to it later (it will take some time). If there won't be large breaking changes the migration should been done.

**Comment by 07akioni** [comment]
Fluent icons may works.
