### ISSUE TITLE
找不到模块“@vicons/ionicons5”或其相应的类型声明 Module "@vicons/ionicons5" or its corresponding type declaration could not be found

### ISSUE THREAD

**Issue by milletlovemouse** [07akioni/xicons#869]
### 问题：
> 在一个项目里，唯独@vicons/ionicons5找不到模块，但是运行时正常，能够正常渲染图标
```typescript
import { Video48Regular, VideoOff48Regular, Video48Filled } from '@vicons/fluent';
import { VideocamOutline } from '@vicons/ionicons5' // 找不到模块“@vicons/ionicons5”或其相应的类型声明。
import { MdVideocam } from '@vicons/ionicons4'
import { VideoCameraOutlined } from '@vicons/antd'
import { PhotoVideo } from '@vicons/fa'
import { FeaturedVideoOutlined } from '@vicons/material'
import { VideoOff } from '@vicons/tabler'
import { VideoAdd } from '@vicons/carbon'
```
![Snipaste_2023-09-09_13-51-25](https://github.com/07akioni/xicons/assets/80803574/a52ec601-d931-41b0-a95c-f393e1507533)

![Snipaste_2023-09-09_13-40-53](https://github.com/07akioni/xicons/assets/80803574/435cbbc3-0018-487d-9838-fd4d620a7ee8)

**Comment by cclearone** [comment]
我也遇到了，使用的naive ui 
![image](https://github.com/07akioni/xicons/assets/57932133/c69167fe-5d14-4c5d-8bcf-e66d6355156a)

**Comment by theOnlyUnique** [comment]
我也遇到了，渲染时直接保存
![image](https://github.com/07akioni/xicons/assets/130697271/b7199b55-7dfe-4b02-a342-5fb41fb746a0)

**Comment by ellie-web** [comment]
it's still a problem in Nuxt 3, any solutions?
