### ISSUE TITLE
在使用vite打包时，产生'EMFILE: too many open files'错误

### ISSUE THREAD

**Issue by AyalaKaguya** [07akioni/xicons#89]
如题

![9fee7b5bde6608e.png](https://user-images.githubusercontent.com/36515540/123790646-24ccb900-d911-11eb-978d-0d71762b15e2.png)

上一次构建是在代码中引入的情况下，而下一条删除了引入，成功的构建。

在使用了rollup设置中的"useFsEvent"后，在Windows上仍然构建失败。

**Comment by AyalaKaguya** [comment]
不过可以直接加载js文件，感觉是vite的问题😅

**Comment by 07akioni** [comment]
> 不过可以直接加载js文件，感觉是vite的问题😅

这个其实是操作系统的配置，`ulimit -n`
